version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: deploy Cloudformation
          command: |
            aws cloudformation deploy --stack-name Stackci --template-file cfn_ec2.yml
      - run:
          name: "Wait Stack Complete"
          command: aws cloudformation wait stack-update-complete --stack-name Stackci


# workflow
workflows:
  cfn_circle:
    jobs:
      - execute-cloudformation